version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: calend_postgres
    environment:
      POSTGRES_USER: calend
      POSTGRES_PASSWORD: calend
      POSTGRES_DB: calend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  postgres_data:
